apiVersion: v1
kind: Service
metadata:
  name: logs-collector-api # Service名
  namespace: logs-system # Namespace
spec:
  type: NodePort
  selector:
    app: logs-collector-api # 転送先Podのラベル
  ports:
    - name: http # REST用
      port: 8080 # ClusterIP側のポート（K8s内部アクセス用）
      targetPort: 8080 # Pod内コンテナのポート
      nodePort: 30080 # ノード（ホスト）からアクセスするための固定ポート
    - name: grpc # gRPC用
      port: 50051
      targetPort: 50051
      nodePort: 30051
